# treefmt configuration
# https://treefmt.com/

[formatter.shfmt]
command = "shfmt"
options = [
  "--indent", "2",      # Use 2-space indentation
  "--case-indent",      # Indent case statements
  "--binary-next-line", # Put binary operators at start of next line
  "--space-redirects",  # Add space after redirection operators
  "--write"             # Write result to file instead of stdout
]
includes = ["*.sh", "*.bash"]

[formatter.prettier]
command = "prettier"
options = ["--write", "--prose-wrap", "never"]
includes = [
  "*.md", "*.markdown",   # Markdown files
  "*.yml", "*.yaml",      # YAML files
  "*.json",               # JSON files
]

[formatter.fourmolu]
command = "fourmolu"
options = ["--mode", "inplace"]
includes = ["*.hs", "*.lhs"]

[formatter.cabal-fmt]
command = "cabal-fmt"
options = ["--inplace"]
includes = ["*.cabal"]

[formatter.nixfmt]
command = "nixfmt"
options = []
includes = ["*.nix"]

[formatter.pretty-uplc]
command = "scripts/pretty-uplc.sh"
options = []
includes = ["*.uplc"]

# Global settings
[global]
excludes = [
  # Exclude nix-specific directories and files
  "result",
  "result-*",
  ".direnv/**",

  # Exclude temporary and build directories
  "node_modules/**",
  "dist/**",
  "build/**",
  ".git/**",
  "dist-newstyle/**",

  # Exclude specific files that shouldn't be formatted
  "flake.lock",

  # Exclude any auto-generated files
  "**/*.generated.*",

  # Exclude Slidev presentations (YAML frontmatter incompatible with Prettier)
  "doc/slides/**"
]
