name: CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Nothing but Nix - Optimize disk space
        uses: wimpysworld/nothing-but-nix@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Use Cachix (pull/push if token provided)
        uses: cachix/cachix-action@v14
        with:
          name: uplc-cape
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build measure executable
        run: nix build .#measure --accept-flake-config -o result

      - name: Build plinth-submissions executable
        run: nix build .#plinth-submissions --accept-flake-config -o result-plinth

      - name: Run Haskell test suite
        run: nix flake check --accept-flake-config

      - name: Verify all submissions
        run: nix develop --accept-flake-config --command bash -c "echo 'Checking result/bin:' && ls -lh result/bin/ && export PATH=\"\$PWD/result/bin:\$PATH\" && cape submission verify --all --verbose"
