name: CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Use Cachix (pull/push if token provided)
        uses: cachix/cachix-action@v14
        with:
          name: uplc-cape
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run test suite
        run: nix develop --accept-flake-config --command cape test

      - name: Verify all submissions
        run: nix develop --accept-flake-config --command cape submission verify --all
