name: Verify dev tooling and validate submissions

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Verify dev tooling and validate submissions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Use Cachix (pull/push if token provided)
        uses: cachix/cachix-action@v14
        with:
          name: uplc-cape
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build Nix dev shell
        run: |
          echo "=== Building dev shell derivation ==="
          nix build --impure --accept-flake-config .#devShells.x86_64-linux.default

      - name: Warm up Nix dev shell (test command execution)
        run: |
          echo "=== Testing dev shell execution ==="
          nix develop --impure --accept-flake-config --command cape --help > /dev/null

      - name: Verify all submissions
        run: |
          echo "=== Running submission verification ==="
          nix develop --impure --accept-flake-config --command cape submission verify --all

      - name: Run test suite
        run: |
          echo "=== Running test suite ==="
          nix develop --impure --accept-flake-config --command cape test
