name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "submissions/**"

# Allow only one concurrent deployment per PR
concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if submission data changed
        id: check_changes
        run: |
          # Check if .uplc or metadata.json files changed compared to main
          if git diff --name-only origin/main...HEAD | grep -qE 'submissions/.*\.(uplc|metadata\.json)$'; then
            echo "Submission data files changed, proceeding with report generation"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No submission data changes detected (only docs/README), skipping deployment"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Nothing but Nix - Optimize disk space
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: wimpysworld/nothing-but-nix@v1

      - name: Install Nix
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Use Cachix (pull/push if token provided)
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: cachix/cachix-action@v14
        with:
          name: uplc-cape
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build measure executable
        if: steps.check_changes.outputs.has_changes == 'true'
        run: nix build .#measure --accept-flake-config -o result

      - name: Measure all submissions
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          nix develop --accept-flake-config --command bash -c "export PATH=\"\$PWD/result/bin:\$PATH\" && cape submission measure --all"

      - name: Generate HTML reports
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          nix develop --accept-flake-config --command bash -c "export PATH=\"\$PWD/result/bin:\$PATH\" && cape submission report --all"

      - name: Deploy to GitHub Pages
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true

      - name: Post preview link comment
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          message: |
            ## 🚀 PR Preview Deployed

            Preview URL: https://intersectmbo.github.io/UPLC-CAPE/pr-${{ github.event.pull_request.number }}/

            The preview site is automatically updated on every push to this PR and will be removed when the PR is closed.

      - name: Skip message
        if: steps.check_changes.outputs.has_changes == 'false'
        run: |
          echo "ℹ️  No submission data changes detected. Skipping report generation."
          echo "Only documentation or README files were modified in the submissions/ directory."
